name: Test
on: [push, pull_request]
env:
  GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
  GO111MODULE: "on"
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure CMake
        run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc ..
      - name: Build Shared Library
        run: |
          cd build
          cmake --build . --config Release
          sudo cp ../lib/*.so /usr/lib/

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.23"
      - name: Install Go dependencies
        run: |
          go mod download
      - name: Run Unit Tests
        run: |
          go test -tags noasm -race -covermode atomic -coverprofile=profile.cov ./...
          go test -race ./...
      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
